# ~/.tmuxinator/default.yml

name: main
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t default

startup_window: Terminals

windows:
  - irssi:
    - screen -t Freenode irssi -c Freenode
  - "arivarton development": 
      # layout: a678,272x49,0,0[273x38,0,0,1,273x11,0,39{103x11,0,39,5,169x11,104,39,6}]
      layout: c952,272x49,0,0[273x45,0,0,1,273x4,0,46{103x4,0,46,5,169x4,104,46,6}]
      panes:
          - cd Devops/ansible/playbooks/arivarton; vim -S Session.vim
          - cd Devops/ansible/playbooks/arivarton; clear
          - cd Devops/ansible/playbooks/arivarton; clear
  - "Web Dev":
      # layout: 94e5,272x49,0,0[272x38,0,0,2,272x10,0,39{103x10,0,39,7,168x10,104,39,8}]
      layout: 8522,272x49,0,0[272x39,0,0,2,272x9,0,40{102x9,0,40,7,169x9,103,40,8}]
      panes:
          - cd ~/Development/www/Django/arivarton; vim -S Session.vim
          - cd ~/Development/www/Django/arivarton; ./manage.py runserver
          - cd ~/Development/www/Django/arivarton && clear
  - "General Term":
      layout: main-horizontal
      panes:
          - 
          - eval clear 
  - rTorrent:
    - rtorrent
